blacklisted_districts:
  - district_srw_commercial
  - district_rw_generator
  - district_rw_commercial
  - district_rw_science
  - district_rw_farming
  - district_cosmogenesis_goverment
  - district_generator_uncapped
  - district_mining_uncapped
  - district_farming_uncapped
  - district_photosynthesis_fields_uncapped
  - district_hollow_mountains_uncapped
  - district_orchard_forests_uncapped
  - district_prison_industrial
  - district_battle_thrall
  - district_arcology_leisure
