district_direct_outputs:
  district_crashed_slaver_ship:
  - alloys
  - research
  - trade
  - unity
  district_generator:
  - energy
  district_mining:
  - minerals
  district_farming:
  - food
  district_geothermal:
  - energy
  district_melting:
  - minerals
  district_hab_energy:
  - energy
  district_hab_mining:
  - minerals
  district_hab_science:
  - research
  district_rw_city:
  - trade
  district_rw_nexus:
  - energy
  district_photosynthesis_fields:
  - energy
  district_hollow_mountains:
  - minerals
  district_orchard_forests:
  - food
  district_ark_generator:
  - energy
  district_ark_military:
  - unity
  - research
  district_ark_forever_cruise:
  - consumer_goods
  - unity
  - trade
