job_tag_outputs:
  energy:
    - energy
  minerals:
    - minerals
  food:
    - food
  alloys:
    - alloys
  consumer_goods:
    - consumer_goods
  trade:
    - trade
  unity:
    - unity
  research:
    - research
  physics_research:
    - physics_research
  society_research:
    - society_research
  engineering_research:
    - engineering_research
  rare_crystals:
    - rare_crystals
  volatile_motes:
    - volatile_motes
  exotic_gases:
    - exotic_gases
