manual_building_destruction:
  - buildings:
      - building_shroud_observatory_1
      - building_ranger_lodge
    triggers:
      - bca_can_remove_building_reasearch

  - buildings:
      - building_archaeo_refinery
      - building_crystal_plant
      - building_chemical_plant
      - building_refinery
    triggers:
      - bca_can_remove_building_industry

  - buildings:
      - building_crystal_plant
      - building_chemical_plant
      - building_refinery
    triggers:
      - bca_advanced_rare_resource_building_replace

  - buildings:
      - building_robot_assembly_plant
      - building_robot_assembly_complex
      - building_machine_assembly_plant
      - building_machine_assembly_complex
      - building_clone_vats
      - building_posthumous_employment_center
      - building_spawning_pool
      - building_offspring_nest
    triggers:
      - bca_can_remove_pop_assemble
