trade:
  - trade
industrial:
  - alloys
  - consumer_goods
foundry:
  - alloys
factory:
  - consumer_goods
research:
  - research
physics:
  - research
society:
  - research
engineering:
  - research
bureaucrat:
  - unity
unity:
  - unity
priest:
  - unity
energy:
  - energy
betharian:
  - energy
minerals:
  - minerals
food:
  - food
angler:
  - food
agrarian:
  - food
hydroponics:
  - food
wilderness_foundry:
  - alloys
wilderness_research:
  - research
wilderness_unity:
  - unity
wilderness_trade:
  - trade
wilderness_minerals:
  - minerals
wilderness_energy:
  - energy
wilderness_food:
  - food
ark_research_unity_consumer_goods:
  - research
  - unity
  - consumer_goods
ark_research_alloys_support:
  - research
  - alloys
