designation_contexts:
  farming:
    job_provider_districts:
      - district_farming
    subcases:
      bca_is_farming_habitat: {}

  generator:
    job_provider_districts:
      - district_generator
    subcases:
      bca_is_generator_betharian: {}

  mining:
    job_provider_districts:
      - district_mining
      - district_melting
