- designations:
    - col_wilderness_capital
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_brain_node_1
        - building_natural_furnace_1
      strategy: job_only

- designations:
    - col_wilderness_generator
  zone_types:
    - wilderness_energy
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_bioelectric_stimulator_1
      strategy: job_only

- designations:
    - col_wilderness_mining
  zone_types:
    - wilderness_minerals
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_churning_tunnels_1
      strategy: job_only

- designations:
    - col_wilderness_farming
  zone_types:
    - wilderness_food
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_massive_growth_1
      strategy: job_only

- designations:
    - col_wilderness_fortress
  zone_types:
    - wilderness_fortress
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_planetary_carapace
      strategy: job_only

- designations:
    - col_wilderness_tech
  zone_types:
    - wilderness_research
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_brain_node_1
      strategy: job_only

- designations:
    - col_wilderness_nest
  zone_types:
    - wilderness_trade
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_tendril_cradle_1
        - building_brain_node_1
      strategy: job_only

- designations:
    - col_wilderness_refinery
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_natural_furnace_1
        - building_churning_stomach
        - building_crystal_growth
        - building_mote_aggravator
      strategy: job_only

- designations:
    - col_wilderness_forge
  zone_types:
    - wilderness_foundry
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_natural_furnace_1
      strategy: job_only

- designations:
    - col_wilderness_unification
  zone_types:
    - wilderness_unity
  groups:
    - buildings:
        - building_cradle_of_rebirth
      strategy: job_bookend

    - buildings:
        - building_commensal_clearing_1
      strategy: job_only

