import os
import re
import shutil
import yaml
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

# --- 配置区 ---
SOURCE_DIR = os.path.dirname(__file__)  # mod_builder 目录
ROOT_DIR = os.path.dirname(SOURCE_DIR)   # Mod 根目录
GENERATED_CONFIG_DIR = os.path.join(SOURCE_DIR, 'templates', 'generated_configs')
TEMPLATE_DIR = os.path.join(SOURCE_DIR, 'templates')
TPL_COMMON_DIR = os.path.join(TEMPLATE_DIR, 'common')
TPL_EVENTS_DIR = os.path.join(TEMPLATE_DIR, 'events')
TPL_INTERFACE_DIR = os.path.join(TEMPLATE_DIR, 'interface')
TPL_LOCALISATION_DIR = os.path.join(TEMPLATE_DIR, 'localisation')
OUTPUT_GUI_DIR = os.path.join(ROOT_DIR, 'interface')

# --- Jinja 环境设置 ---
# 允许从 TEMPLATE_DIR 加载（包括 component/ 子目录）
env = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    trim_blocks=True,      # 自动移除标签后的第一个换行符
    lstrip_blocks=True     # 自动移除标签前的空白
)

GENERATED_WARNING_LINES = [
    "# ====================================================================",
    "# WARNING: This file is generated. Do not edit this file directly.",
    "# Direct changes will be overwritten by the next render/build step.",
    "# Edit the corresponding source template or upstream config instead.",
    "# ====================================================================",
]
MODIFIER_DOC_PATH = (
    Path.home()
    / "Documents"
    / "Paradox Interactive"
    / "Stellaris"
    / "logs"
    / "script_documentation"
    / "modifiers.log"
)
MODIFIER_LINE_RE = re.compile(r"^-\s*([A-Za-z0-9_:.\-]+),\s*Category:")


def load_known_modifiers(path=MODIFIER_DOC_PATH):
    """读取游戏导出的 modifier 文档，作为模板渲染时的白名单。"""
    if not path.exists():
        print(f"⚠️ 警告: modifier 文档不存在: {path}")
        return set()

    modifiers = set()
    with open(path, "r", encoding="utf-8-sig", errors="ignore") as f:
        for line in f:
            match = MODIFIER_LINE_RE.match(line.strip())
            if match:
                modifiers.add(match.group(1))
    print(f"加载 Modifier 文档: {len(modifiers)} modifiers")
    return modifiers

def load_configs():
    """合并 generated_configs 文件夹下的所有 yaml 配置"""
    full_config = {}
    if not os.path.exists(GENERATED_CONFIG_DIR):
        print(f"⚠️ 警告: 配置目录不存在: {GENERATED_CONFIG_DIR}")
        return full_config

    for filename in os.listdir(GENERATED_CONFIG_DIR):
        if filename.endswith(('.yaml', '.yml')):
            with open(os.path.join(GENERATED_CONFIG_DIR, filename), 'r', encoding='utf-8') as f:
                data = yaml.safe_load(f)
                if data:
                    full_config.update(data)
    return full_config


def prepend_generated_warning(content, template_path):
    """为生成文件添加统一的头部警告。"""
    warning_lines = GENERATED_WARNING_LINES + [f"# Source template: {template_path}", ""]
    warning_block = "\n".join(warning_lines)
    return f"{warning_block}{content}"


def render_to_file(template_path, output_path, config_data, encoding='utf-8'):
    template = env.get_template(template_path)
    content = template.render(**config_data)
    content = prepend_generated_warning(content, template_path)

    with open(output_path, 'w', encoding=encoding) as f:
        f.write(content)

def build():
    print("开始生成 Mod 文件...")

    # 1. 加载所有配置数据
    config_data = load_configs()
    config_data["known_modifiers"] = load_known_modifiers()


    # 3. 渲染所有 .gui.j2 文件
    for filename in os.listdir(TPL_INTERFACE_DIR):
        if filename.endswith('.j2'):
            tpl_path = f'interface/{filename}' # 相对路径供 Jinja 加载
            output_name = filename.replace('.j2', '')
            output_path = os.path.join(OUTPUT_GUI_DIR, output_name)

            print(f"渲染 GUI: {filename} -> {output_name}")
            render_to_file(tpl_path, output_path, config_data)
    # 3.1. 渲染所有 .txt.j2 文件
    for root, _, files in os.walk(TPL_COMMON_DIR):
        for filename in files:
            if filename.endswith('.txt.j2'):
                full_path = os.path.join(root, filename)
                # 生成 Jinja 模板相对路径（使用 '/'）
                rel_path = os.path.relpath(full_path, TEMPLATE_DIR)
                tpl_path = rel_path.replace(os.path.sep, '/')
                output_name = filename.replace('.j2', '')
                # 将输出放到 Mod 根目录下对应的相对位置（保留 common/ 子目录结构）
                output_dir = os.path.join(ROOT_DIR, os.path.dirname(rel_path))
                os.makedirs(output_dir, exist_ok=True)
                output_path = os.path.join(output_dir, output_name)
                print(f"渲染 Common: {rel_path} -> {os.path.relpath(output_path, ROOT_DIR)}")
                render_to_file(tpl_path, output_path, config_data)
    for root, _, files in os.walk(TPL_EVENTS_DIR):
        for filename in files:
            if filename.endswith('.txt.j2'):
                full_path = os.path.join(root, filename)
                rel_path = os.path.relpath(full_path, TEMPLATE_DIR)
                tpl_path = rel_path.replace(os.path.sep, '/')
                output_name = filename.replace('.j2', '')
                output_dir = os.path.join(ROOT_DIR, os.path.dirname(rel_path))
                os.makedirs(output_dir, exist_ok=True)
                output_path = os.path.join(output_dir, output_name)
                print(f"渲染 Events: {rel_path} -> {os.path.relpath(output_path, ROOT_DIR)}")
                render_to_file(tpl_path, output_path, config_data)
    LANG_DIRS = ['english', 'simp_chinese', 'japanese', 'russian']
    LANG_PREFIXES = {
        'english': 'l_english',
        'simp_chinese': 'l_simp_chinese',
        'japanese': 'l_japanese',
        'russian': 'l_russian',
    }

    for root, _, files in os.walk(TPL_LOCALISATION_DIR):
        for filename in files:
            if filename.endswith('.yml.j2'):
                full_path = os.path.join(root, filename)
                rel_path = os.path.relpath(full_path, TEMPLATE_DIR)
                tpl_path = rel_path.replace(os.path.sep, '/')
                output_name = filename.replace('.j2', '')
                rel_dir = os.path.dirname(rel_path)

                # 判断是否是 all: 模板（直接在 localisation/ 根下，无语言子目录）
                is_all_template = (os.path.normpath(rel_dir) == 'localisation')

                if is_all_template:
                    # all: → 渲染一次，替换语言头 + 文件名 _all → _<lang>，输出到各语言目录
                    template = env.get_template(tpl_path)
                    content = template.render(**config_data)
                    base_name = output_name.replace('_all', '')
                    for lang_key, lang_prefix in LANG_PREFIXES.items():
                        lang_content = content.replace('all:', f'{lang_prefix}:')
                        lang_output_name = base_name.replace('.yml', f'_{lang_key}.yml')
                        output_dir = os.path.join(ROOT_DIR, 'localisation', lang_key)
                        os.makedirs(output_dir, exist_ok=True)
                        output_path = os.path.join(output_dir, lang_output_name)
                        with open(output_path, 'w', encoding='utf-8-sig') as f:
                            f.write(prepend_generated_warning(lang_content, tpl_path))
                    print(f"渲染 Localisation(all): {rel_path} -> localisation/<lang>/{base_name}_{{lang}}.yml")
                else:
                    output_dir = os.path.join(ROOT_DIR, rel_dir)
                    os.makedirs(output_dir, exist_ok=True)
                    output_path = os.path.join(output_dir, output_name)
                    print(f"渲染 Localisation: {rel_path} -> {os.path.relpath(output_path, ROOT_DIR)}")
                    render_to_file(tpl_path, output_path, config_data, encoding='utf-8-sig')

    print("生成完成！")

if __name__ == "__main__":
    build()
