import os
import re
import sys
import yaml
from dataclasses import dataclass
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

try:
    from .formatters import format_pdx_code
    from .normalize_localisation_encoding import normalize_localisation_encoding
except ImportError:
    from formatters import format_pdx_code
    from normalize_localisation_encoding import normalize_localisation_encoding

# --- 配置区 ---
SOURCE_DIR = os.path.dirname(__file__)  # mod_builder 目录
ROOT_DIR = os.path.dirname(SOURCE_DIR)   # Mod 根目录
GENERATED_CONFIG_DIR = os.path.join(SOURCE_DIR, 'templates', 'generated_configs')
TEMPLATE_DIR = os.path.join(SOURCE_DIR, 'templates')
TPL_COMMON_DIR = os.path.join(TEMPLATE_DIR, 'common')
TPL_EVENTS_DIR = os.path.join(TEMPLATE_DIR, 'events')
TPL_INTERFACE_DIR = os.path.join(TEMPLATE_DIR, 'interface')
TPL_LOCALISATION_DIR = os.path.join(TEMPLATE_DIR, 'localisation')
OUTPUT_GUI_DIR = os.path.join(ROOT_DIR, 'interface')
RGIGNORE_PATH = Path(ROOT_DIR) / ".rgignore"

# --- Jinja 环境设置 ---
# 允许从 TEMPLATE_DIR 加载（包括 component/ 子目录）
env = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    trim_blocks=True,      # 自动移除标签后的第一个换行符
    lstrip_blocks=True     # 自动移除标签前的空白
)

GENERATED_WARNING_LINES = [
    "# ====================================================================",
    "# WARNING: This file is generated. Do not edit this file directly.",
    "# ====================================================================",
]
RGIGNORE_GENERATED_OUTPUT_START = "# BEGIN generated by mod_builder/generate.py: generated search-ignored files"
RGIGNORE_GENERATED_OUTPUT_END = "# END generated by mod_builder/generate.py: generated search-ignored files"
RGIGNORE_LEGACY_GENERATED_TXT_START = "# BEGIN generated by mod_builder/generate.py: generated .txt files"
RGIGNORE_LEGACY_GENERATED_TXT_END = "# END generated by mod_builder/generate.py: generated .txt files"
RGIGNORE_GENERATED_OUTPUT_SUFFIXES = {".txt", ".yml", ".gui", ".gfx"}
MODIFIER_DOC_PATH = (
    Path.home()
    / "Documents"
    / "Paradox Interactive"
    / "Stellaris"
    / "logs"
    / "script_documentation"
    / "modifiers.log"
)
MODIFIER_LINE_RE = re.compile(r"^-\s*([A-Za-z0-9_:.\-]+),\s*Category:")
IDENTIFIER_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_:.|$@]*\b")
SUBMOD_METADATA_RE = re.compile(
    r"^#\s*submod\s+(?P<name>[A-Za-z0-9_.-]+)"
    r"(?:\s+file_name\s+(?P<file_name>[^\s]+))?\s*$"
)
COMPILE_VARIANTS_RE = re.compile(
    r"^#\s*compile_variants(?:\s+(?P<variants>[A-Za-z0-9_.\-\s]+))?\s*$"
)


@dataclass(frozen=True)
class TemplateMetadata:
    submod: str | None = None
    published_file_name: str | None = None
    compile_variants: tuple[str, ...] = ()


@dataclass(frozen=True)
class RenderVariant:
    name: str
    output_name: str
    submod: str | None = None
    published_file_name: str | None = None


def read_template_metadata(template_path):
    """Read optional build metadata from the first template line."""
    full_path = Path(TEMPLATE_DIR) / template_path
    with full_path.open("r", encoding="utf-8-sig") as template_file:
        first_line = template_file.readline().rstrip("\r\n")

    submod_match = SUBMOD_METADATA_RE.fullmatch(first_line)
    if submod_match:
        return TemplateMetadata(
            submod=submod_match.group("name"),
            published_file_name=submod_match.group("file_name"),
        )

    variants_match = COMPILE_VARIANTS_RE.fullmatch(first_line)
    if variants_match:
        variants = tuple((variants_match.group("variants") or "").split())
        if not variants or variants[0] != "main":
            raise ValueError(
                f"{template_path}: compile_variants must start with the main variant"
            )
        if len(set(variants)) != len(variants):
            raise ValueError(f"{template_path}: compile_variants contains duplicates")
        return TemplateMetadata(compile_variants=variants)

    return TemplateMetadata()


def strip_rendered_template_metadata(content):
    """Remove source-only build metadata after Jinja rendering."""
    lines = content.splitlines(keepends=True)
    if not lines:
        return content
    first_line = lines[0].rstrip("\r\n")
    if SUBMOD_METADATA_RE.fullmatch(first_line) or COMPILE_VARIANTS_RE.fullmatch(first_line):
        return "".join(lines[1:])
    return content


def variant_output_name(output_name, variant):
    """Keep the main filename stable and suffix additional IDE-visible variants."""
    if variant == "main":
        return output_name
    output_path = Path(output_name)
    return f"{output_path.stem}_{variant}{output_path.suffix}"


def get_render_variants(template_path, output_name):
    metadata = read_template_metadata(template_path)
    if metadata.compile_variants:
        return [
            RenderVariant(
                name=variant,
                output_name=variant_output_name(output_name, variant),
                submod=None if variant == "main" else variant,
                published_file_name=None if variant == "main" else output_name,
            )
            for variant in metadata.compile_variants
        ]

    return [
        RenderVariant(
            name=metadata.submod or "development",
            output_name=output_name,
            submod=metadata.submod,
            published_file_name=metadata.published_file_name,
        )
    ]


def load_known_modifiers(path=MODIFIER_DOC_PATH):
    """读取游戏导出的 modifier 文档，作为模板渲染时的白名单。"""
    if not path.exists():
        print(f"⚠️ 警告: modifier 文档不存在: {path}")
        return set()

    modifiers = set()
    with open(path, "r", encoding="utf-8-sig", errors="ignore") as f:
        for line in f:
            match = MODIFIER_LINE_RE.match(line.strip())
            if match:
                modifiers.add(match.group(1))
    print(f"加载 Modifier 文档: {len(modifiers)} modifiers")
    return modifiers

def load_configs():
    """合并 generated_configs 文件夹下的所有 yaml 配置"""
    full_config = {}
    if not os.path.exists(GENERATED_CONFIG_DIR):
        print(f"⚠️ 警告: 配置目录不存在: {GENERATED_CONFIG_DIR}")
        return full_config

    for filename in os.listdir(GENERATED_CONFIG_DIR):
        if filename.endswith(('.yaml', '.yml')):
            with open(os.path.join(GENERATED_CONFIG_DIR, filename), 'r', encoding='utf-8') as f:
                data = yaml.safe_load(f)
                if data:
                    full_config.update(data)
    return full_config


def prepend_generated_warning(
    content,
    template_path,
    *,
    submod=None,
    published_file_name=None,
):
    """为生成文件添加统一的头部警告。"""
    publish_lines = []
    if submod:
        publish_line = f"# submod {submod}"
        if published_file_name:
            publish_line += f" file_name {published_file_name}"
        publish_lines.append(publish_line)
    warning_lines = GENERATED_WARNING_LINES + [f"# Source template: {template_path}", "\n\n"]
    warning_block = "\n".join(publish_lines + warning_lines)
    return f"{warning_block}{content}"


def strip_comments_and_strings(content):
    """Remove quoted strings and comments before identifier counting."""
    cleaned_lines = []
    for line in content.splitlines():
        chars = []
        in_quote = False
        escaped = False
        for char in line:
            if escaped:
                escaped = False
                if in_quote:
                    chars.append(" ")
                else:
                    chars.append(char)
                continue
            if char == "\\":
                escaped = True
                chars.append(" " if in_quote else char)
                continue
            if char == '"':
                in_quote = not in_quote
                chars.append(" ")
                continue
            if char == "#" and not in_quote:
                break
            chars.append(" " if in_quote else char)
        cleaned_lines.append("".join(chars))
    return "\n".join(cleaned_lines)


def collect_generated_stats(rel_output_path, content):
    """Collect simple size/identifier stats for generated PDX files."""
    non_empty_lines = sum(1 for line in content.splitlines() if line.strip())
    identifier_count = len(IDENTIFIER_RE.findall(strip_comments_and_strings(content)))
    return {
        "path": rel_output_path.replace(os.path.sep, "/"),
        "non_empty_lines": non_empty_lines,
        "identifier_count": identifier_count,
    }


def print_identifier_stats(stats):
    total_identifiers = sum(item["identifier_count"] for item in stats)
    if total_identifiers <= 0:
        print("生成统计: common/events 无可统计标识符")
        return

    print("生成统计: common/events 标识符 Top 5")
    for item in sorted(stats, key=lambda x: x["identifier_count"], reverse=True)[:5]:
        ratio = item["identifier_count"] / total_identifiers * 100
        print(f"  {item['path']}: {item['non_empty_lines']} 非空行, {ratio:.2f}%")


def rgignore_pattern_for_output_path(rel_output_path):
    """Return a repo-root anchored .rgignore pattern for a generated output."""
    return f"/{Path(rel_output_path).as_posix()}"


def replace_rgignore_generated_block(existing, block_text):
    existing = existing.lstrip("\ufeff")
    block_patterns = (
        (
            RGIGNORE_GENERATED_OUTPUT_START,
            RGIGNORE_GENERATED_OUTPUT_END,
        ),
        (
            RGIGNORE_LEGACY_GENERATED_TXT_START,
            RGIGNORE_LEGACY_GENERATED_TXT_END,
        ),
    )
    updated = existing
    replaced = False
    for start_marker, end_marker in block_patterns:
        block_re = re.compile(
            rf"{re.escape(start_marker)}.*?"
            rf"{re.escape(end_marker)}\r?\n?",
            re.DOTALL,
        )
        if block_re.search(updated):
            updated = block_re.sub(block_text if not replaced else "", updated)
            replaced = True

    if not replaced:
        separator = "" if not existing or existing.endswith(("\n", "\r\n")) else "\n"
        updated = f"{existing}{separator}{block_text}"

    return updated


def update_directory_rgignore(directory, file_names):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    patterns = sorted(set(file_names))
    block_lines = [
        RGIGNORE_GENERATED_OUTPUT_START,
        "# Generated files in this directory. Search source templates/config instead.",
        *patterns,
        RGIGNORE_GENERATED_OUTPUT_END,
    ]
    block_text = "\n".join(block_lines) + "\n"
    rgignore_path = directory / ".rgignore"
    existing = ""
    if rgignore_path.exists():
        existing = rgignore_path.read_text(encoding="utf-8-sig")
    rgignore_path.write_text(
        replace_rgignore_generated_block(existing, block_text),
        encoding="utf-8",
    )


def update_generated_output_directory_rgignores(generated_output_paths, root_dir):
    files_by_dir = {}
    for path in generated_output_paths:
        rel_path = Path(path)
        if rel_path.suffix not in RGIGNORE_GENERATED_OUTPUT_SUFFIXES:
            continue
        files_by_dir.setdefault(rel_path.parent, set()).add(rel_path.name)

    root_dir = Path(root_dir)
    for rel_dir, file_names in files_by_dir.items():
        update_directory_rgignore(root_dir / rel_dir, file_names)


def update_generated_output_rgignore(generated_output_paths, rgignore_path=RGIGNORE_PATH):
    """Maintain the generated-output block in .rgignore without touching manual rules."""
    patterns = sorted(
        {
            rgignore_pattern_for_output_path(path)
            for path in generated_output_paths
            if Path(path).suffix in RGIGNORE_GENERATED_OUTPUT_SUFFIXES
        }
    )
    block_lines = [
        RGIGNORE_GENERATED_OUTPUT_START,
        "# Runtime files generated from mod_builder/templates.",
        "# Search the source templates/config instead of these generated outputs.",
        *patterns,
        RGIGNORE_GENERATED_OUTPUT_END,
    ]
    block_text = "\n".join(block_lines) + "\n"

    rgignore_path = Path(rgignore_path)
    existing = ""
    if rgignore_path.exists():
        existing = rgignore_path.read_text(encoding="utf-8-sig")

    rgignore_path.write_text(
        replace_rgignore_generated_block(existing, block_text),
        encoding="utf-8",
    )
    update_generated_output_directory_rgignores(
        generated_output_paths,
        rgignore_path.parent,
    )


def should_format_generated_output(template_path):
    """Only format PDX-like generated files; localisation YAML keeps its own layout."""
    return template_path.endswith((".txt.j2", ".gui.j2", ".gfx.j2"))


def render_to_file(
    template_path,
    output_path,
    config_data,
    encoding='utf-8',
    *,
    render_variant=None,
):
    template = env.get_template(template_path)
    variant = render_variant or RenderVariant(
        name="development",
        output_name=Path(output_path).name,
    )
    variant_config = dict(config_data)
    variant_config["build_variant"] = variant.name
    variant_config["enabled_submods"] = (
        {variant.name} if variant.submod else set()
    )
    content = strip_rendered_template_metadata(template.render(**variant_config))
    if should_format_generated_output(template_path):
        content = format_pdx_code(content)
    output_content = prepend_generated_warning(
        content,
        template_path,
        submod=variant.submod,
        published_file_name=variant.published_file_name,
    )

    with open(output_path, 'w', encoding=encoding) as f:
        f.write(output_content)

    return content

def build():
    print("开始生成 Mod 文件...")
    generated_stats = []
    generated_output_paths = []

    # 1. 加载所有配置数据
    config_data = load_configs()
    config_data["known_modifiers"] = load_known_modifiers()


    # 3. 渲染所有 .gui.j2 文件
    for filename in os.listdir(TPL_INTERFACE_DIR):
        if filename.endswith('.j2'):
            tpl_path = f'interface/{filename}' # 相对路径供 Jinja 加载
            output_name = filename.replace('.j2', '')
            for variant in get_render_variants(tpl_path, output_name):
                output_path = os.path.join(OUTPUT_GUI_DIR, variant.output_name)
                render_to_file(
                    tpl_path,
                    output_path,
                    config_data,
                    render_variant=variant,
                )
                generated_output_paths.append(os.path.relpath(output_path, ROOT_DIR))
    # 3.1. 渲染所有 .txt.j2 文件
    for root, _, files in os.walk(TPL_COMMON_DIR):
        for filename in files:
            if filename.endswith('.txt.j2'):
                full_path = os.path.join(root, filename)
                # 生成 Jinja 模板相对路径（使用 '/'）
                rel_path = os.path.relpath(full_path, TEMPLATE_DIR)
                tpl_path = rel_path.replace(os.path.sep, '/')
                output_name = filename.replace('.j2', '')
                # 将输出放到 Mod 根目录下对应的相对位置（保留 common/ 子目录结构）
                output_dir = os.path.join(ROOT_DIR, os.path.dirname(rel_path))
                os.makedirs(output_dir, exist_ok=True)
                for variant in get_render_variants(tpl_path, output_name):
                    output_path = os.path.join(output_dir, variant.output_name)
                    content = render_to_file(
                        tpl_path,
                        output_path,
                        config_data,
                        render_variant=variant,
                    )
                    generated_stats.append(
                        collect_generated_stats(
                            os.path.relpath(output_path, ROOT_DIR),
                            content,
                        )
                    )
                    generated_output_paths.append(os.path.relpath(output_path, ROOT_DIR))
    for root, _, files in os.walk(TPL_EVENTS_DIR):
        for filename in files:
            if filename.endswith('.txt.j2'):
                full_path = os.path.join(root, filename)
                rel_path = os.path.relpath(full_path, TEMPLATE_DIR)
                tpl_path = rel_path.replace(os.path.sep, '/')
                output_name = filename.replace('.j2', '')
                output_dir = os.path.join(ROOT_DIR, os.path.dirname(rel_path))
                os.makedirs(output_dir, exist_ok=True)
                for variant in get_render_variants(tpl_path, output_name):
                    output_path = os.path.join(output_dir, variant.output_name)
                    content = render_to_file(
                        tpl_path,
                        output_path,
                        config_data,
                        render_variant=variant,
                    )
                    generated_stats.append(
                        collect_generated_stats(
                            os.path.relpath(output_path, ROOT_DIR),
                            content,
                        )
                    )
                    generated_output_paths.append(os.path.relpath(output_path, ROOT_DIR))
    LANG_DIRS = ['english', 'simp_chinese', 'japanese', 'russian']
    LANG_PREFIXES = {
        'english': 'l_english',
        'simp_chinese': 'l_simp_chinese',
        'japanese': 'l_japanese',
        'russian': 'l_russian',
    }

    for root, _, files in os.walk(TPL_LOCALISATION_DIR):
        for filename in files:
            if filename.endswith('.yml.j2'):
                full_path = os.path.join(root, filename)
                rel_path = os.path.relpath(full_path, TEMPLATE_DIR)
                tpl_path = rel_path.replace(os.path.sep, '/')
                output_name = filename.replace('.j2', '')
                rel_dir = os.path.dirname(rel_path)

                # 判断是否是 all: 模板（直接在 localisation/ 根下，无语言子目录）
                is_all_template = (os.path.normpath(rel_dir) == 'localisation')

                if is_all_template:
                    # all: → 渲染一次，替换语言头 + 文件名 _all → _<lang>，输出到各语言目录
                    template = env.get_template(tpl_path)
                    base_name = output_name.replace('_all', '')
                    for variant in get_render_variants(tpl_path, base_name):
                        variant_config = dict(config_data)
                        variant_config["build_variant"] = variant.name
                        variant_config["enabled_submods"] = (
                            {variant.name} if variant.submod else set()
                        )
                        content = strip_rendered_template_metadata(
                            template.render(**variant_config)
                        )
                        for lang_key, lang_prefix in LANG_PREFIXES.items():
                            lang_content = re.sub(
                                r"(?m)^all:\s*$",
                                f"{lang_prefix}:",
                                content,
                                count=1,
                            )
                            lang_output_name = variant.output_name.replace(
                                '.yml',
                                f'_{lang_key}.yml',
                            )
                            published_file_name = variant.published_file_name
                            if published_file_name:
                                published_file_name = published_file_name.replace(
                                    '.yml',
                                    f'_{lang_key}.yml',
                                )
                            output_dir = os.path.join(ROOT_DIR, 'localisation', lang_key)
                            os.makedirs(output_dir, exist_ok=True)
                            output_path = os.path.join(output_dir, lang_output_name)
                            with open(output_path, 'w', encoding='utf-8-sig') as f:
                                f.write(
                                    prepend_generated_warning(
                                        lang_content,
                                        tpl_path,
                                        submod=variant.submod,
                                        published_file_name=published_file_name,
                                    )
                                )
                            generated_output_paths.append(
                                os.path.relpath(output_path, ROOT_DIR)
                            )
                else:
                    output_dir = os.path.join(ROOT_DIR, rel_dir)
                    os.makedirs(output_dir, exist_ok=True)
                    for variant in get_render_variants(tpl_path, output_name):
                        output_path = os.path.join(output_dir, variant.output_name)
                        render_to_file(
                            tpl_path,
                            output_path,
                            config_data,
                            encoding='utf-8-sig',
                            render_variant=variant,
                        )
                        generated_output_paths.append(
                            os.path.relpath(output_path, ROOT_DIR)
                        )

    normalize_localisation_encoding(Path(ROOT_DIR) / "localisation")
    update_generated_output_rgignore(generated_output_paths)
    print_identifier_stats(generated_stats)
    scripts_dir = Path(ROOT_DIR) / "scripts"
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))
    from publish_mod import publish

    publish(
        scripts_dir / "publish_mod.yaml",
        dry_run=False,
        verbose=False,
    )
    print("发布完成！")
    print("生成完成！")

if __name__ == "__main__":
    build()
