
secondary_districts_d1:
- district_resort_1
- district_hive_1
- district_nexus_1
- district_arcology_urban_1
- district_rw_urban_1
- district_generator
- district_geothermal
- district_hab_energy
- district_photosynthesis_fields
- district_ark_generator

secondary_districts_d2:
- district_resort_2
- district_hive_2
- district_nexus_2
- district_arcology_urban_2
- district_rw_urban_2
- district_mining
- district_melting
- district_hab_mining
- district_hollow_mountains
- district_ark_military
- district_ark_forever_cruise

secondary_districts_d3:
- district_resort_3
- district_hive_3
- district_nexus_3
- district_arcology_urban_3
- district_rw_urban_3
- district_farming
- district_polytechnic
- district_hab_science
- district_orchard_forests
- district_ark_basic

zone_slot_district_slot_mapping:
    z3: d1
    z4: d2
    z5: d3
